### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by miladlashini** [EMBEDONIX/cpplibs#1]
https://github.com/EMBEDONIX/cpplibs/blob/f0f38ef63948362483267f1c918da7242709c558/libs/fileio/src/filereader.cpp#L24C1-L24C1

IMHO, It would be more efficient if the storage (here vector) is provided by the caller of the interface (as a ref f.e). If I am not mistaken here a vector will be created in function and at the end it will be copied to the return value (f.e for a file with the size of 250k , 500k memory is needed). While in the case that storage is provided by the caller only 250 k will be used. Using move will disable the RVO. Please close the thread yourself when you find the idea not relevant or useful:)

**Comment by SaeidYazdani** [comment]
Thanks for the input. Highly appreciated. Yeah, I never checked to ensure the vector gets copied or moved... I assumed the compiler would issue a move, but that needs to be proven.
I'll check it out.

**Comment by SaeidYazdani** [comment]
> https://github.com/EMBEDONIX/cpplibs/blob/f0f38ef63948362483267f1c918da7242709c558/libs/fileio/src/filereader.cpp#L24C1-L24C1
> 
> IMHO, It would be more efficient if the storage (here vector) is provided by the caller of the interface (as a ref f.e). If I am not mistaken here a vector will be created in function and at the end it will be copied to the return value (f.e for a file with the size of 250k , 500k memory is needed). While in the case that storage is provided by the caller only 250 k will be used. Using move will disable the RVO. Please close the thread yourself when you find the idea not relevant or useful:)

One issue would be that the caller would need to either know the file size in advance or get the file size by other means to create a large enough buffer.
One simple school of thought would be that the function will write as much as size the user-allocated buffer size is.

Any comment on that?

**Comment by SaeidYazdani** [comment]
@miladlashini 
I have added your variant and also a simple benchmark example. For a 10MB files, read 10 times, here are the read results.

mila read: 4
mila read: 4
mila read: 4
mila read: 4
mila read: 4
mila read: 4
mila read: 4
mila read: 4
mila read: 4
mila read: 4
saya read: 6
saya read: 6
saya read: 7
saya read: 6
saya read: 6
saya read: 7
saya read: 6
saya read: 6
saya read: 6
saya read: 6

So there is, of course, a difference. But then again, with your variant, the caller either needs to know the file size or create a big enough array prior to the function call.

**Comment by SaeidYazdani** [comment]
The variant proposed by @miladlashini was added to the library :)
